### ISSUE TITLE
id number for Brazil

### ISSUE THREAD

**Issue by microdataxyz** [microdataxyz/idnumbers#2]
https://en.wikipedia.org/wiki/National_identification_number#Brazil

**Comment by AngusHsu** [comment]
Still looking for doc about the checksum algorithm about RIC for Brazil, putting this in TODO
https://learn.microsoft.com/en-us/microsoft-365/compliance/sit-defn-brazil-national-identification-card?view=o365-worldwide#checksum

**Comment by AngusHsu** [comment]
Closed as issued another in #82
